### ISSUE TITLE
Estrutura condicional da Classe TicketMachine

### ISSUE THREAD

**Issue by Andy-Barbosa** [VitorAcosta/Source-Code-Inspection#1]
Na estrutura condicional que avalia a quantia inserida com os valores possíveis de papel moeda, o índice do vetor "papelMoeda" está definido como 1 e não como i ( 0 <= i <= papelMoeda.length). Assim, sempre será comparada um único valor de papel moeda.

Problema se encontra na linha 25.
![PROBLEMA_1](https://user-images.githubusercontent.com/49701501/159572899-202812fd-e7d1-40c8-9f58-49bda0449a64.png)

**Comment by VitorAcosta** [comment]
Corrigido no commit [444bf58](https://github.com/VitorAcosta/Source-Code-Inspection/commit/444bf5816e61fc448a58d7fa6475a38ee5315733).
