### ISSUE TITLE
Acessando índice inválido na Classe TrocoIterator

### ISSUE THREAD

**Issue by Andy-Barbosa** [VitorAcosta/Source-Code-Inspection#10]
Em ambas as linhas especificadas, existe um acesso do vetor "papeisMoeda" em um índice inexistente, maior que o último índice válido (> 5).
![PROBLEMA_7](https://user-images.githubusercontent.com/49701501/160012864-2dffca77-3a37-45e1-9777-746dae2b57d9.png)

**Comment by VitorAcosta** [comment]
Commit [e07d7ba](https://github.com/VitorAcosta/Source-Code-Inspection/commit/e07d7baa5a7614ad5d10054587899fd3baf1a2d7) corrige a Issue #8 e a Issue atual.
