### ISSUE TITLE
 Acessando índice inválido na Classe TrocoIterator

### ISSUE THREAD

**Issue by Andy-Barbosa** [VitorAcosta/Source-Code-Inspection#13]
Mesmo problema citado na Issue #10 , porém na linha 73. Acessando índice inexistente, maior que o último índice válido (> 5).

**Comment by VitorAcosta** [comment]
Correção implementada no commit [1282140](https://github.com/VitorAcosta/Source-Code-Inspection/commit/1282140cfdc404e87c426e745838e74a693bdbaf).
