### ISSUE TITLE
Ambiguidade no sumário do caso de uso (CSU) 01

### ISSUE THREAD

**Issue by VitorAcosta** [VitorAcosta/Source-Code-Inspection#14]
O caso de uso CSU01 apresentado na Seção 1.3.1 é ambíguo em seu sumário, não sendo claro se o usuário irá inserir a quantia de dinheiro em texto ou se o usuário irá inserir o papel-moeda e o campo de texto mostrará somente a representação do que foi inserido.

### 1.3.1. CSU01 - Inserir dinheiro
| **Identificador**      | CSU01                                                                                                                                           |
|------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------|
| **Nome**               | Inserir dinheiro                                                                                                                                |
| **Atores**             | Cliente                                                                                                                                         |
| **Sumário**            | Uma quantia de dinheiro é inserida na máquina. É importante ressaltar que essa quantia sempre é representada por uma única nota de papel-moeda. |
| **Complexidade**       | Médio                                                                                                                                           |
| **Regras de Negócio**  | N/D                                                                                                                                             |
| **Pré-Condições**      | N/D                                                                                                                                             |
| **Pós-Condição**       | O valor inserido é adicionado ao saldo total disponível.                                                                                        |
| **Pontos de Inclusão** | N/D                                                                                                                                             |
| **Pontos de Extensão** | N/D                                                                                                                                             |

**Comment by Andy-Barbosa** [comment]
Commit d5897b2b3dd052a5b95b2c8ec36fc5415a7e1b06 resolvido.
