### ISSUE TITLE
Retorno do Iterator na Classe Troco

### ISSUE THREAD

**Issue by Andy-Barbosa** [VitorAcosta/Source-Code-Inspection#4]
O método indica que o retorno é do tipo Iterator, o retorno correto deveria ser TrocoIterator.
![PROBLEMA_4](https://user-images.githubusercontent.com/49701501/160009306-884b6630-4b37-43bf-a95b-ddfd7f7f5240.png)

**Comment by Andy-Barbosa** [comment]
Commit [e1ffcbb](https://github.com/VitorAcosta/Source-Code-Inspection/commit/e1ffcbb2fa8bed18f5210abcab93187c2920eb3b) foi resolvido.

**Comment by Andy-Barbosa** [comment]
O commit citado não foi resolvido. Uma vez, que o tipo "Troco.TrocoIterator" não é genérico, portanto não pode ser parametrizado com argumentos.

**Comment by VitorAcosta** [comment]
Resolvido com o commit [e45af75](https://github.com/VitorAcosta/Source-Code-Inspection/commit/e45af757e2336bd74d2b092ad7430f4d54f3d8df).
