### ISSUE TITLE
Laço infinito do método HasNext() na Classe TrocoIterator

### ISSUE THREAD

**Issue by Andy-Barbosa** [VitorAcosta/Source-Code-Inspection#8]
O método HasNext(), por convenção deveria começar no índice zero do vetor e percorrê-lo até o índice final possível. Da forma que foi criado, o laço além de progredir "infinitamente", ele também não indica se após o elemento atual existe um próximo elemento, pois começa sempre da posição 6, que é fora do vetor.
![PROBLEMA_5](https://user-images.githubusercontent.com/49701501/160011805-089b4a82-8267-40c3-af40-ed8816f3b699.png)

**Comment by VitorAcosta** [comment]
Commit [e07d7ba](https://github.com/VitorAcosta/Source-Code-Inspection/commit/e07d7baa5a7614ad5d10054587899fd3baf1a2d7) resolve a Issue apresentada.

**Comment by Andy-Barbosa** [comment]
![photo_2022-03-25_18-49-37](https://user-images.githubusercontent.com/49701501/160207100-8c8b3b5c-1569-4df0-a37a-6ee64d0c79b8.jpg)
A condição do laço for sempre será falsa. É necessário inverter o "maior igual" para "menor".

**Comment by VitorAcosta** [comment]
Commit [c98ed53](https://github.com/VitorAcosta/Source-Code-Inspection/commit/c98ed537f766a6185f498cfb389e121d512fde2a) resolve a nova abertura da Issue.
